# Generated by Django 5.2.8 on 2026-01-06 09:02

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("transactions", "Transactions"),
                            ("treasury", "Treasury"),
                            ("workflow", "Workflow"),
                            ("reports", "Reports"),
                        ],
                        help_text="Internal app name (lowercase)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="User-friendly display name", max_length=100
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        help_text="URL path for this app (e.g., /transactions/)",
                        max_length=200,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="What this app does"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this app is currently available",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("staff", "Staff"),
                            ("treasury", "Treasury"),
                            ("fp&a", "FP&A"),
                            ("department_head", "Department Head"),
                            ("branch_manager", "Branch Manager"),
                            ("regional_manager", "Regional Manager"),
                            ("group_finance_manager", "Group Finance Manager"),
                            ("cfo", "CFO"),
                            ("ceo", "CEO"),
                        ],
                        default="staff",
                        max_length=30,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "is_centralized_approver",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this user can approve requisitions for the whole company regardless of branch/region/department.",
                    ),
                ),
                ("failed_login_attempts", models.PositiveIntegerField(default=0)),
                ("lockout_until", models.DateTimeField(blank=True, null=True)),
                ("last_failed_login", models.DateTimeField(blank=True, null=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("last_login_user_agent", models.TextField(blank=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.company",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.costcenter",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.department",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "position_title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.position",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.region",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "assigned_apps",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Applications this user has access to. Use Django permissions to control add/view/change/delete within each app.",
                        related_name="users",
                        to="accounts.app",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address to send invitation to", max_length=254
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, help_text="Recipient's first name", max_length=150
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, help_text="Recipient's last name", max_length=150
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Role to assign when user accepts invitation",
                        max_length=30,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token for invitation link",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Invitation expiration date/time"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, help_text="When invitation was accepted", null=True
                    ),
                ),
                (
                    "assigned_apps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of app names to assign when user accepts",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.department",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="Admin who sent this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User account created from this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Invitation",
                "verbose_name_plural": "User Invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceAccessAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("device_name", models.CharField(max_length=255)),
                ("user_agent", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "was_allowed",
                    models.BooleanField(help_text="Whether access was granted"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for allow/block decision",
                        max_length=255,
                    ),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request_path",
                    models.CharField(
                        blank=True, help_text="URL path being accessed", max_length=500
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_access_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Access Attempt",
                "verbose_name_plural": "Device Access Attempts",
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["-attempted_at"], name="accounts_de_attempt_ae19e2_idx"
                    ),
                    models.Index(
                        fields=["user", "-attempted_at"],
                        name="accounts_de_user_id_e84372_idx",
                    ),
                    models.Index(
                        fields=["was_allowed", "-attempted_at"],
                        name="accounts_de_was_all_957f3a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "User Created"),
                            ("update", "User Updated"),
                            ("delete", "User Deleted"),
                            ("activate", "User Activated"),
                            ("deactivate", "User Deactivated"),
                            ("password_reset", "Password Reset Sent"),
                            ("role_change", "Role Changed"),
                            ("app_assign", "Apps Assigned"),
                            ("permission_change", "Permissions Changed"),
                            ("group_change", "Groups Changed"),
                        ],
                        help_text="Type of action performed",
                        max_length=30,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the action occurred",
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="Details of what changed (before/after values)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional context or reason for the change",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the admin who made the change",
                        null=True,
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        help_text="User who was affected by this action",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Audit Log",
                "verbose_name_plural": "User Audit Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="accounts_us_timesta_b897ba_idx"
                    ),
                    models.Index(
                        fields=["target_user", "-timestamp"],
                        name="accounts_us_target__beaf3c_idx",
                    ),
                    models.Index(
                        fields=["performed_by", "-timestamp"],
                        name="accounts_us_perform_93cf73_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WhitelistedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        help_text="Friendly device name (e.g., 'Windows 10 - Chrome')",
                        max_length=255,
                    ),
                ),
                ("user_agent", models.TextField(help_text="Full user agent string")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address when device was registered"
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="Hash of device characteristics (screen resolution, timezone, etc.)",
                        max_length=64,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location when device was registered (City, Country)",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this device is currently allowed",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this the user's primary device?"
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this device was used to access the system",
                    ),
                ),
                (
                    "registration_method",
                    models.CharField(
                        choices=[
                            ("signup", "During Signup"),
                            ("manual", "Manual Addition"),
                            ("self_service", "Self-Service Portal"),
                        ],
                        default="signup",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about this device"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whitelisted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Whitelisted Device",
                "verbose_name_plural": "Whitelisted Devices",
                "ordering": ["-is_primary", "-last_used_at"],
                "unique_together": {("user", "user_agent", "ip_address")},
            },
        ),
    ]
