# Generated by Django 5.2.8 on 2025-11-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_centralized_approver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("superuser", "Superuser"),
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("treasury", "Treasury"),
                    ("fp&a", "FP&A"),
                    ("department_head", "Department Head"),
                    ("branch_manager", "Branch Manager"),
                    ("regional_manager", "Regional Manager"),
                    ("group_finance_manager", "Group Finance Manager"),
                    ("cfo", "CFO"),
                    ("ceo", "CEO"),
                ],
                default="staff",
                max_length=30,
            ),
        ),
    ]
