# Generated by Django 5.2.8 on 2025-11-23 10:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_add_app_model_and_assignments"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email address to send invitation to", max_length=254
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, help_text="Recipient's first name", max_length=150
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, help_text="Recipient's last name", max_length=150
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="Role to assign when user accepts invitation",
                        max_length=30,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique token for invitation link",
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Invitation expiration date/time"),
                ),
                (
                    "accepted_at",
                    models.DateTimeField(
                        blank=True, help_text="When invitation was accepted", null=True
                    ),
                ),
                (
                    "assigned_apps",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of app names to assign when user accepts",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.company",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organization.department",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        help_text="Admin who sent this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User account created from this invitation",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Invitation",
                "verbose_name_plural": "User Invitations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceAccessAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("device_name", models.CharField(max_length=255)),
                ("user_agent", models.TextField()),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "was_allowed",
                    models.BooleanField(help_text="Whether access was granted"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Reason for allow/block decision",
                        max_length=255,
                    ),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request_path",
                    models.CharField(
                        blank=True, help_text="URL path being accessed", max_length=500
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_access_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Access Attempt",
                "verbose_name_plural": "Device Access Attempts",
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["-attempted_at"], name="accounts_de_attempt_ae19e2_idx"
                    ),
                    models.Index(
                        fields=["user", "-attempted_at"],
                        name="accounts_de_user_id_e84372_idx",
                    ),
                    models.Index(
                        fields=["was_allowed", "-attempted_at"],
                        name="accounts_de_was_all_957f3a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WhitelistedDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        help_text="Friendly device name (e.g., 'Windows 10 - Chrome')",
                        max_length=255,
                    ),
                ),
                ("user_agent", models.TextField(help_text="Full user agent string")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address when device was registered"
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="Hash of device characteristics (screen resolution, timezone, etc.)",
                        max_length=64,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location when device was registered (City, Country)",
                        max_length=255,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this device is currently allowed",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Is this the user's primary device?"
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this device was used to access the system",
                    ),
                ),
                (
                    "registration_method",
                    models.CharField(
                        choices=[
                            ("signup", "During Signup"),
                            ("manual", "Manual Addition"),
                            ("self_service", "Self-Service Portal"),
                        ],
                        default="signup",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes about this device"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whitelisted_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Whitelisted Device",
                "verbose_name_plural": "Whitelisted Devices",
                "ordering": ["-is_primary", "-last_used_at"],
                "unique_together": {("user", "user_agent", "ip_address")},
            },
        ),
    ]
