# Generated by Django 5.2.8 on 2025-11-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_userinvitation_deviceaccessattempt_whitelisteddevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
