# Generated by Django 5.2.8 on 2025-11-30 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_add_sla_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='validation_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for treasury validation', null=True),
        ),
        migrations.AddField(
            model_name='requisition',
            name='validation_status',
            field=models.CharField(choices=[('not_validated', 'Not Validated'), ('pending_validation', 'Pending Validation'), ('treasury_change_requested', 'Treasury Change Requested'), ('validated', 'Validated')], default='not_validated', max_length=32),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('pending_changes', 'Pending Changes from Requester'), ('pending_validation', 'Pending Validation (Treasury)'), ('pending_urgency_confirmation', 'Pending Urgency Confirmation'), ('pending_dept_approval', 'Pending Department Approval'), ('pending_branch_approval', 'Pending Branch Approval'), ('pending_regional_review', 'Pending Regional Review'), ('pending_finance_review', 'Pending Finance Review'), ('pending_treasury_validation', 'Pending Treasury Validation'), ('pending_cfo_approval', 'Pending CFO Approval'), ('paid', 'Paid'), ('validated', 'Validated'), ('reviewed', 'Reviewed'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
        migrations.CreateModel(
            name='ValidationTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('validated', 'Validated'), ('validation_changes_requested', 'Validation Changes Requested'), ('validation_failed', 'Validation Failed'), ('validation_note', 'Validation Note')], max_length=30)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.requisition')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
