# Generated by Django 5.2.8 on 2026-01-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0012_add_expense_category_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requisition",
            name="approval_deadline",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="end_to_end_sla_deadline",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="expense_category",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="payment_sla_deadline",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="validation_deadline",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="validation_status",
        ),
        migrations.RemoveField(
            model_name="requisition",
            name="vendor_name",
        ),
        migrations.AlterField(
            model_name="requisition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("pending_changes", "Pending Changes from Requester"),
                    ("pending_urgency_confirmation", "Pending Urgency Confirmation"),
                    ("pending_dept_approval", "Pending Department Approval"),
                    ("pending_branch_approval", "Pending Branch Approval"),
                    ("pending_regional_review", "Pending Regional Review"),
                    ("pending_finance_review", "Pending Finance Review"),
                    ("pending_treasury_validation", "Pending Treasury Validation"),
                    ("pending_cfo_approval", "Pending CFO Approval"),
                    ("paid", "Paid"),
                    ("reviewed", "Reviewed"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="ValidationTrail",
        ),
    ]
