# Generated by Django 5.2.8 on 2025-12-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('reports', '0002_report_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, help_text='If null, annual budget')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='organization.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='organization.company')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='organization.costcenter')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets', to='organization.department')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'year', 'month'], name='reports_bud_company_ye_ba1d9e_idx'), models.Index(fields=['branch', 'department', 'cost_center'], name='reports_bud_branch_de_de9e17_idx')],
                'unique_together': {('company', 'branch', 'department', 'cost_center', 'year', 'month')},
            },
        ),
    ]
