# Generated by Django 5.2.8 on 2026-01-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_report_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="report",
            options={
                "permissions": [
                    ("view_reports_dashboard", "Can view Reports dashboard"),
                    (
                        "view_transaction_report",
                        "Can view Transaction report and exports",
                    ),
                    (
                        "view_treasury_report",
                        "Can view Treasury report, drilldowns, and exports",
                    ),
                    ("view_approval_report", "Can view Approval analytics and exports"),
                    ("view_user_activity_report", "Can view User Activity report"),
                    (
                        "view_stuck_approvals_report",
                        "Can view Stuck Approvals exception report",
                    ),
                    (
                        "view_threshold_overrides_report",
                        "Can view Threshold Overrides report and exports",
                    ),
                    (
                        "view_budget_vs_actuals_report",
                        "Can view Budget vs Actuals report and exports",
                    ),
                ]
            },
        ),
        migrations.RenameIndex(
            model_name="budgetallocation",
            new_name="reports_bud_company_fe8382_idx",
            old_name="reports_bud_company_ye_ba1d9e_idx",
        ),
        migrations.RenameIndex(
            model_name="budgetallocation",
            new_name="reports_bud_branch__0a5471_idx",
            old_name="reports_bud_branch_de_de9e17_idx",
        ),
    ]
