# Generated by Django 5.2.8 on 2025-11-23 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('backup_type', models.CharField(choices=[('full', 'Full Backup'), ('incremental', 'Incremental Backup'), ('database_only', 'Database Only'), ('media_only', 'Media Files Only'), ('settings_only', 'Settings Only'), ('pre_maintenance', 'Pre-Maintenance Backup'), ('pre_reset', 'Pre-Factory Reset'), ('scheduled', 'Scheduled Backup'), ('manual', 'Manual Backup')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('corrupted', 'Corrupted'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database_file', models.FileField(blank=True, null=True, upload_to='backups/database/')),
                ('media_archive', models.FileField(blank=True, null=True, upload_to='backups/media/')),
                ('settings_file', models.FileField(blank=True, null=True, upload_to='backups/settings/')),
                ('file_size_bytes', models.BigIntegerField(default=0, help_text='Total backup size in bytes')),
                ('database_size_bytes', models.BigIntegerField(default=0)),
                ('media_size_bytes', models.BigIntegerField(default=0)),
                ('is_restorable', models.BooleanField(default=True)),
                ('restore_tested', models.BooleanField(default=False)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('records_count', models.JSONField(default=dict, help_text='Count of records per model at backup time')),
                ('system_version', models.CharField(blank=True, max_length=50)),
                ('django_version', models.CharField(blank=True, max_length=50)),
                ('python_version', models.CharField(blank=True, max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_protected', models.BooleanField(default=False, help_text="Protected backups won't be auto-deleted")),
                ('error_message', models.TextField(blank=True)),
                ('completion_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FactoryResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('reset_database', models.BooleanField(default=False)),
                ('reset_media_files', models.BooleanField(default=False)),
                ('reset_settings', models.BooleanField(default=False)),
                ('keep_users', models.BooleanField(default=False)),
                ('keep_organizations', models.BooleanField(default=False)),
                ('confirmation_code', models.CharField(max_length=50)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending_confirmation', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('recovery_backup_id', models.CharField(blank=True, help_text='Backup ID for emergency recovery', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pre_reset_backup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reset_operations', to='system_maintenance.backuprecord')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Reason for maintenance')),
                ('estimated_duration_minutes', models.IntegerField(default=30, help_text='Estimated maintenance duration')),
                ('expected_completion', models.DateTimeField(blank=True, null=True)),
                ('notify_users', models.BooleanField(default=True)),
                ('custom_message', models.TextField(blank=True, help_text='Custom message to display during maintenance')),
                ('completed_successfully', models.BooleanField(default=False)),
                ('completion_notes', models.TextField(blank=True)),
                ('activated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_maintenance', to=settings.AUTH_USER_MODEL)),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_maintenance', to=settings.AUTH_USER_MODEL)),
                ('pre_maintenance_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_sessions', to='system_maintenance.backuprecord')),
            ],
            options={
                'ordering': ['-activated_at'],
                'get_latest_by': 'activated_at',
            },
        ),
        migrations.CreateModel(
            name='RestorePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restore_point_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('restoring', 'Restoring'), ('restored', 'Restored'), ('failed', 'Failed'), ('superseded', 'Superseded')], default='ready', max_length=20)),
                ('system_state', models.JSONField(default=dict, help_text='Snapshot of critical system settings and state')),
                ('last_restored_at', models.DateTimeField(blank=True, null=True)),
                ('restore_count', models.IntegerField(default=0)),
                ('is_automatic', models.BooleanField(default=False)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restore_points', to='system_maintenance.backuprecord')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('last_restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restored_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemHealthCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('overall_status', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('success', 'Success')], max_length=20)),
                ('health_score', models.IntegerField(default=100, help_text='Overall health score (0-100)')),
                ('checks_performed', models.JSONField(default=dict, help_text='Detailed results of individual checks')),
                ('critical_issues', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('database_size_mb', models.FloatField(default=0)),
                ('disk_usage_percent', models.FloatField(default=0)),
                ('memory_usage_percent', models.FloatField(default=0)),
                ('backup_age_days', models.FloatField(default=0)),
                ('orphaned_records_count', models.IntegerField(default=0)),
                ('missing_files_count', models.IntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0)),
                ('slow_queries_count', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['-created_at'], name='system_main_created_b2e4e6_idx'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['status'], name='system_main_status_047571_idx'),
        ),
        migrations.AddIndex(
            model_name='backuprecord',
            index=models.Index(fields=['backup_type'], name='system_main_backup__11a6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthcheck',
            index=models.Index(fields=['-performed_at'], name='system_main_perform_e6f544_idx'),
        ),
        migrations.AddIndex(
            model_name='systemhealthcheck',
            index=models.Index(fields=['overall_status'], name='system_main_overall_fd128f_idx'),
        ),
    ]
