# Generated by Django 5.2.8 on 2026-01-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system_maintenance", "0002_alter_maintenancemode_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintenancemode",
            options={"get_latest_by": "activated_at", "ordering": ["-activated_at"]},
        ),
    ]
