# Generated by Django 5.2.8 on 2025-11-16 10:29

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0001_initial"),
        ("transactions", "0003_approvaltrail_skipped_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "payment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("mpesa", "MPESA"),
                            ("bank", "Bank Transfer"),
                            ("cash", "Cash"),
                        ],
                        default="mpesa",
                        max_length=10,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        help_text="Phone number, account, or recipient name",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("executing", "Executing"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("reconciled", "Reconciled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("execution_timestamp", models.DateTimeField(blank=True, null=True)),
                ("otp_required", models.BooleanField(default=True)),
                ("otp_sent_timestamp", models.DateTimeField(blank=True, null=True)),
                ("otp_verified", models.BooleanField(default=False)),
                ("otp_verified_timestamp", models.DateTimeField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requisition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="transactions.requisition",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentExecution",
            fields=[
                (
                    "execution_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("execution_timestamp", models.DateTimeField(auto_now_add=True)),
                ("gateway_reference", models.CharField(max_length=255, unique=True)),
                ("gateway_status", models.CharField(max_length=50)),
                ("otp_verified_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "executor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_executions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "otp_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution",
                        to="treasury.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Execution",
                "verbose_name_plural": "Payment Executions",
                "ordering": ["-execution_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="TreasuryFund",
            fields=[
                (
                    "fund_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=14
                    ),
                ),
                (
                    "reorder_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50000.00"),
                        help_text="Minimum balance threshold. Auto-triggers ReplenishmentRequest when exceeded.",
                        max_digits=14,
                    ),
                ),
                ("last_replenished", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treasury_funds",
                        to="organization.branch",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treasury_funds",
                        to="organization.company",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treasury_funds",
                        to="organization.region",
                    ),
                ),
            ],
            options={
                "verbose_name": "Treasury Fund",
                "verbose_name_plural": "Treasury Funds",
            },
        ),
        migrations.CreateModel(
            name="ReplenishmentRequest",
            fields=[
                (
                    "request_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "requested_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("funded", "Funded"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_replenishment_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "treasury_fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replenishment_requests",
                        to="treasury.treasuryfund",
                    ),
                ),
            ],
            options={
                "verbose_name": "Replenishment Request",
                "verbose_name_plural": "Replenishment Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "entry_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("debit", "Debit (Payment Out)"),
                            ("credit", "Credit (Replenishment In)"),
                            ("adjustment", "Adjustment (Variance)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reconciled", models.BooleanField(default=False)),
                (
                    "reconciliation_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reconciled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciled_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="treasury.paymentexecution",
                    ),
                ),
                (
                    "treasury_fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="treasury.treasuryfund",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ledger Entry",
                "verbose_name_plural": "Ledger Entries",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="VarianceAdjustment",
            fields=[
                (
                    "adjustment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "adjusted_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "variance_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="initiated_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "treasury_fund",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variances",
                        to="treasury.treasuryfund",
                    ),
                ),
            ],
            options={
                "verbose_name": "Variance Adjustment",
                "verbose_name_plural": "Variance Adjustments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["requisition", "status"], name="treasury_pa_requisi_4de032_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="treasury_pa_status_44e7e1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="treasuryfund",
            unique_together={("company", "region", "branch")},
        ),
    ]
