# Generated by Django 5.2.8 on 2025-11-22 13:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0007_payment_mpesa_fields"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="alert",
            new_name="treasury_al_alert_t_e77360_idx",
            old_name="treasury_al_alert_t_idx",
        ),
        migrations.RenameIndex(
            model_name="alert",
            new_name="treasury_al_resolve_78098c_idx",
            old_name="treasury_al_resolve_idx",
        ),
        migrations.RenameIndex(
            model_name="dashboardmetric",
            new_name="treasury_da_dashboa_1456c4_idx",
            old_name="treasury_da_dashboa_idx",
        ),
        migrations.RenameIndex(
            model_name="dashboardmetric",
            new_name="treasury_da_metric__145c6c_idx",
            old_name="treasury_da_metric__idx",
        ),
        migrations.RenameIndex(
            model_name="fundforecast",
            new_name="treasury_fu_fund_id_08a34f_idx",
            old_name="treasury_fu_fund_id_idx",
        ),
        migrations.RenameIndex(
            model_name="fundforecast",
            new_name="treasury_fu_needs_r_7889bc_idx",
            old_name="treasury_fu_needs_r_idx",
        ),
        migrations.AlterField(
            model_name="fundforecast",
            name="recommended_replenishment_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="treasurydashboard",
            name="pending_replenishment_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="treasurydashboard",
            name="pending_variance_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="treasurydashboard",
            name="total_amount_this_month",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="treasurydashboard",
            name="total_amount_this_week",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="treasurydashboard",
            name="total_amount_today",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=14
            ),
        ),
        migrations.AlterField(
            model_name="treasurydashboard",
            name="total_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=16
            ),
        ),
        migrations.AlterField(
            model_name="treasurydashboard",
            name="total_utilization_pct",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="varianceadjustment",
            name="original_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=14,
                null=True,
            ),
        ),
    ]
