# Generated by Django 5.2.8 on 2025-11-23 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def check_and_add_fields(apps, schema_editor):
    """
    Check if columns exist before adding them to avoid conflicts
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if columns exist (SQLite compatible)
        cursor.execute("PRAGMA table_info('treasury_payment')")
        existing_columns = {row[1] for row in cursor.fetchall()}
        
        # Add created_by_id if it doesn't exist
        if 'created_by_id' not in existing_columns:
            cursor.execute("""
                ALTER TABLE treasury_payment 
                ADD COLUMN created_by_id INTEGER NULL 
                REFERENCES accounts_customuser(id) 
                ON DELETE SET NULL;
            """)
            cursor.execute("""
                CREATE INDEX treasury_payment_created_by_id_idx 
                ON treasury_payment(created_by_id);
            """)
        
        # Add description if it doesn't exist
        if 'description' not in existing_columns:
            cursor.execute("""
                ALTER TABLE treasury_payment 
                ADD COLUMN description TEXT NULL;
            """)
        
        # Add voucher_number if it doesn't exist
        if 'voucher_number' not in existing_columns:
            cursor.execute("""
                ALTER TABLE treasury_payment 
                ADD COLUMN voucher_number VARCHAR(50) NULL UNIQUE;
            """)


def make_requisition_optional(apps, schema_editor):
    """
    Make requisition field nullable if it isn't already
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Check if requisition_id is nullable (SQLite compatible)
        cursor.execute("PRAGMA table_info('treasury_payment')")
        columns = cursor.fetchall()
        for col in columns:
            if col[1] == 'requisition_id' and col[3] == 1:  # 1 means NOT NULL
                cursor.execute("ALTER TABLE treasury_payment ALTER COLUMN requisition_id DROP NOT NULL;")


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_requisition_change_request_deadline_and_more'),
        ('treasury', '0008_rename_treasury_al_alert_t_idx_treasury_al_alert_t_e77360_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(check_and_add_fields, reverse_code=migrations.RunPython.noop),
        migrations.RunPython(make_requisition_optional, reverse_code=migrations.RunPython.noop),
    ]
