# Generated by Django 5.2.8 on 2025-11-30 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("transactions", "0010_add_sla_fields"),
        ("treasury", "0010_payment_fields_safe_add"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    # Perform DB-level operations only on PostgreSQL; SQLite can't run these statements
                    code=lambda apps, schema_editor: (
                        schema_editor.execute(
                            """
                            ALTER TABLE treasury_treasuryfund ADD COLUMN auto_replenish boolean;
                            ALTER TABLE treasury_treasuryfund ADD COLUMN department_id integer;
                            ALTER TABLE treasury_treasuryfund ADD COLUMN min_balance numeric(14,2);
                        """
                        )
                        if schema_editor.connection.vendor == "postgresql"
                        else print(
                            "Non-postgres DB detected: skipping Add Column DB-level operations"
                        )
                    ),
                    reverse_code=lambda apps, schema_editor: (
                        schema_editor.execute(
                            """
                            ALTER TABLE treasury_payment DROP COLUMN IF EXISTS created_by_id;
                            ALTER TABLE treasury_payment DROP COLUMN IF EXISTS description;
                            ALTER TABLE treasury_payment DROP COLUMN IF EXISTS voucher_number;
                            ALTER TABLE treasury_treasuryfund DROP COLUMN IF EXISTS auto_replenish;
                            ALTER TABLE treasury_treasuryfund DROP COLUMN IF EXISTS department_id;
                            ALTER TABLE treasury_treasuryfund DROP COLUMN IF EXISTS min_balance;
                        """
                        )
                        if schema_editor.connection.vendor == "postgresql"
                        else print(
                            "Non-postgres DB detected: skipping Drop Column DB-level operations"
                        )
                    ),
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="treasuryfund",
                    name="auto_replenish",
                    field=models.BooleanField(
                        blank=True,
                        help_text="Override auto-replenishment for this fund. If null, uses system default.",
                        null=True,
                    ),
                ),
                migrations.AddField(
                    model_name="treasuryfund",
                    name="department",
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treasury_funds",
                        to="organization.department",
                    ),
                ),
                migrations.AddField(
                    model_name="treasuryfund",
                    name="min_balance",
                    field=models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum allowed balance for this fund. Overrides system default if set.",
                        max_digits=14,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="payment",
            name="requisition",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated requisition (optional for bulk uploads)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="transactions.requisition",
            ),
        ),
        migrations.RunPython(
            # Add unique constraint only on PostgreSQL, skip if already exists
            code=lambda apps, schema_editor: (
                schema_editor.execute(
                    """
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM pg_constraint WHERE conname = 'treasury_treasuryfund_company_id_region_id_branch_id_department_id_uniq'
                        ) THEN
                            ALTER TABLE treasury_treasuryfund 
                            ADD CONSTRAINT treasury_treasuryfund_company_id_region_id_branch_id_department_id_uniq 
                            UNIQUE (company_id, region_id, branch_id, department_id);
                        END IF;
                    END
                    $$;
                """
                )
                if schema_editor.connection.vendor == "postgresql"
                else print(
                    "Non-postgres DB detected: skipping UNIQUE constraint addition"
                )
            ),
            reverse_code=lambda apps, schema_editor: (
                schema_editor.execute(
                    """
                    ALTER TABLE treasury_treasuryfund 
                    DROP CONSTRAINT IF EXISTS treasury_treasuryfund_company_id_region_id_branch_id_department_id_uniq;
                """
                )
                if schema_editor.connection.vendor == "postgresql"
                else print("Non-postgres DB detected: skipping UNIQUE constraint drop")
            ),
        ),
    ]
