# Generated by Django 5.2.8 on 2025-11-30 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('transactions', '0010_add_sla_fields'),
        ('treasury', '0011_alter_treasuryfund_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='treasuryfund',
            unique_together=set(),
        ),
        # The following fields may already exist on some DBs. We apply DB-side ALTER
        # statements idempotently, and update the migration state via
        # SeparateDatabaseAndState so Django's model state includes these fields.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='''
            ALTER TABLE treasury_payment ADD COLUMN IF NOT EXISTS created_by_id integer;
            ALTER TABLE treasury_payment ADD COLUMN IF NOT EXISTS description text;
            ALTER TABLE treasury_payment ADD COLUMN IF NOT EXISTS snapshot_amount numeric(14,2);
            ALTER TABLE treasury_payment ADD COLUMN IF NOT EXISTS snapshot_branch_id integer;
            ALTER TABLE treasury_payment ADD COLUMN IF NOT EXISTS snapshot_company_id integer;
            ALTER TABLE treasury_payment ADD COLUMN IF NOT EXISTS snapshot_description text;
            ALTER TABLE treasury_payment ADD COLUMN IF NOT EXISTS snapshot_destination varchar(255);
            ALTER TABLE treasury_payment ADD COLUMN IF NOT EXISTS voucher_number varchar(50);
            ALTER TABLE treasury_treasuryfund ADD COLUMN IF NOT EXISTS auto_replenish boolean;
            ALTER TABLE treasury_treasuryfund ADD COLUMN IF NOT EXISTS department_id integer;
            ALTER TABLE treasury_treasuryfund ADD COLUMN IF NOT EXISTS min_balance numeric(14,2);
                    ''',
                    reverse_sql='''
            ALTER TABLE treasury_payment DROP COLUMN IF EXISTS created_by_id;
            ALTER TABLE treasury_payment DROP COLUMN IF EXISTS description;
            ALTER TABLE treasury_payment DROP COLUMN IF EXISTS snapshot_amount;
            ALTER TABLE treasury_payment DROP COLUMN IF EXISTS snapshot_branch_id;
            ALTER TABLE treasury_payment DROP COLUMN IF EXISTS snapshot_company_id;
            ALTER TABLE treasury_payment DROP COLUMN IF EXISTS snapshot_description;
            ALTER TABLE treasury_payment DROP COLUMN IF EXISTS snapshot_destination;
            ALTER TABLE treasury_payment DROP COLUMN IF EXISTS voucher_number;
            ALTER TABLE treasury_treasuryfund DROP COLUMN IF EXISTS auto_replenish;
            ALTER TABLE treasury_treasuryfund DROP COLUMN IF EXISTS department_id;
            ALTER TABLE treasury_treasuryfund DROP COLUMN IF EXISTS min_balance;
                    ''',
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='payment',
                    name='created_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='description',
                    field=models.TextField(blank=True, help_text='Purpose of payment', null=True),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='snapshot_amount',
                    field=models.DecimalField(blank=True, decimal_places=2, help_text='Immutable copy of requisition.amount at payment creation', max_digits=14, null=True),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='snapshot_branch',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_payments', to='organization.branch'),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='snapshot_company',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshot_payments', to='organization.company'),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='snapshot_description',
                    field=models.TextField(blank=True, help_text='Immutable copy of description/purpose at payment creation', null=True),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='snapshot_destination',
                    field=models.CharField(blank=True, help_text='Immutable copy of destination at payment creation', max_length=255, null=True),
                ),
                migrations.AddField(
                    model_name='payment',
                    name='voucher_number',
                    field=models.CharField(blank=True, help_text='Unique voucher/document number for M-Pesa bulk payments', max_length=50, null=True, unique=True),
                ),
                migrations.AddField(
                    model_name='treasuryfund',
                    name='auto_replenish',
                    field=models.BooleanField(blank=True, help_text='Override auto-replenishment for this fund. If null, uses system default.', null=True),
                ),
                migrations.AddField(
                    model_name='treasuryfund',
                    name='department',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasury_funds', to='organization.department'),
                ),
                migrations.AddField(
                    model_name='treasuryfund',
                    name='min_balance',
                    field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed balance for this fund. Overrides system default if set.', max_digits=14, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='payment',
            name='requisition',
            field=models.ForeignKey(blank=True, help_text='Associated requisition (optional for bulk uploads)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='transactions.requisition'),
        ),
        migrations.AlterUniqueTogether(
            name='treasuryfund',
            unique_together={('company', 'region', 'branch', 'department')},
        ),
    ]
