# Generated by Django 5.2.8 on 2025-12-09 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0011_voucher_number_unique_constraint"),
        ("treasury", "0012_alter_treasuryfund_unique_together_and_more"),
    ]

    operations = []
