# Generated by Django 5.2.8 on 2026-01-08 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0015_remove_payment_snapshot_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="snapshot_amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="snapshot_branch",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="snapshot_company",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="snapshot_description",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="snapshot_destination",
        ),
    ]
