# Generated by Django 5.2.8 on 2025-11-23 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Created"),
                            ("update", "Updated"),
                            ("delete", "Deleted"),
                            ("view", "Viewed"),
                            ("login", "Logged In"),
                            ("logout", "Logged Out"),
                            ("permission_change", "Permission Changed"),
                            ("setting_change", "Setting Changed"),
                            ("user_action", "User Action"),
                            ("system", "System Action"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of object affected (e.g., 'Requisition', 'User')",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the affected object",
                        max_length=255,
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the object",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Details about what happened"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        help_text="Before/after values for updates",
                        null=True,
                    ),
                ),
                (
                    "success",
                    models.BooleanField(
                        default=True, help_text="Whether the action succeeded"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error details if action failed"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Log",
                "verbose_name_plural": "Activity Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp", "user"],
                        name="settings_ma_timesta_4611d4_idx",
                    ),
                    models.Index(
                        fields=["action", "-timestamp"],
                        name="settings_ma_action_dc178a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Setting identifier (e.g., DEFAULT_APPROVAL_DEADLINE_HOURS)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name shown in UI", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Explanation of what this setting does"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("email", "Email Configuration"),
                            ("approval", "Approval Workflow"),
                            ("payment", "Payment Settings"),
                            ("security", "Security & Authentication"),
                            ("notifications", "Notifications"),
                            ("general", "General Settings"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                (
                    "setting_type",
                    models.CharField(
                        choices=[
                            ("string", "Text"),
                            ("integer", "Number"),
                            ("boolean", "True/False"),
                            ("json", "JSON/Object"),
                            ("email", "Email Address"),
                            ("url", "URL"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("value", models.TextField(help_text="Current value of the setting")),
                ("default_value", models.TextField(help_text="Default/fallback value")),
                (
                    "is_sensitive",
                    models.BooleanField(
                        default=False,
                        help_text="Hide value in UI (for passwords, API keys)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this setting is currently in use",
                    ),
                ),
                (
                    "editable_by_admin",
                    models.BooleanField(
                        default=True,
                        help_text="Can be changed through UI or requires code change",
                    ),
                ),
                (
                    "requires_restart",
                    models.BooleanField(
                        default=False,
                        help_text="Requires server restart to take effect",
                    ),
                ),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_modified_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settings_modified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
                "ordering": ["category", "display_name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="settings_ma_categor_e5a6a5_idx",
                    )
                ],
            },
        ),
    ]
