# Generated by Django 5.2.8 on 2025-11-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_manager', '0002_add_treasury_settings'),
        ('settings_manager', '0005_activitylog_location_alter_activitylog_user_agent'),
    ]

    operations = [
    ]
