from django.core.management.base import BaseCommand

from settings_manager.models import SystemSetting


class Command(BaseCommand):
    help = "Seed default system settings"

    def handle(self, *args, **options):
        created_count = 0
        updated_count = 0

        settings = [
            # APPROVAL SETTINGS
            {
                "key": "ALLOW_SELF_APPROVAL",
                "display_name": "Allow Self-Approval",
                "description": "Allow users to approve their own requisitions (Not recommended)",
                "category": "approval",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "APPROVAL_ESCALATION_ENABLED",
                "display_name": "Enable Approval Escalation",
                "description": "Automatically escalate to next approver if deadline expires",
                "category": "approval",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "APPROVAL_NOTIFICATION_ENABLED",
                "display_name": "Enable Approval Notifications",
                "description": "Send notifications for approval actions",
                "category": "approval",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "AUTO_REJECT_EXPIRED_CHANGES",
                "display_name": "Auto-Reject Expired Change Requests",
                "description": "Automatically reject requisitions when change request deadline expires",
                "category": "approval",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "AUTO_REJECT_PENDING_AFTER_HOURS",
                "display_name": "Auto-Reject Pending After (Hours)",
                "description": "Automatically reject requisition if pending longer than this value",
                "category": "approval",
                "setting_type": "integer",
                "value": "72",
                "default_value": "72",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "DEFAULT_APPROVAL_DEADLINE_HOURS",
                "display_name": "Default Approval Deadline (Hours)",
                "description": "Default number of hours for an approval action before escalation or auto-reject",
                "category": "approval",
                "setting_type": "integer",
                "value": "24",
                "default_value": "24",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "DEFAULT_CHANGE_REQUEST_DEADLINE_HOURS",
                "display_name": "Default Change Request Deadline (Hours)",
                "description": "Default number of hours for requester to respond to change requests",
                "category": "approval",
                "setting_type": "integer",
                "value": "48",
                "default_value": "48",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "FAST_TRACK_ENABLED",
                "display_name": "Enable Fast-Track Approvals",
                "description": "Allow urgent requisitions to skip intermediate approvers",
                "category": "approval",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "MAX_APPROVALS_PER_REQUISITION",
                "display_name": "Max Approvals Per Requisition",
                "description": "Maximum number of approval steps allowed per requisition",
                "category": "approval",
                "setting_type": "integer",
                "value": "5",
                "default_value": "5",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "MAX_REQUISITION_AMOUNT",
                "display_name": "Maximum Requisition Amount",
                "description": "Maximum amount allowed for a single requisition",
                "category": "approval",
                "setting_type": "integer",
                "value": "1000000",
                "default_value": "1000000",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            # EMAIL SETTINGS
            {
                "key": "EMAIL_REPLY_TO",
                "display_name": "Email Reply-To Address",
                "description": "Reply-to email address for system notifications",
                "category": "email",
                "setting_type": "email",
                "value": "support@pettycash.local",
                "default_value": "support@pettycash.local",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "EMAIL_SUBJECT_PREFIX",
                "display_name": "Email Subject Prefix",
                "description": "Prefix added to all email subjects",
                "category": "email",
                "setting_type": "string",
                "value": "[Petty Cash System]",
                "default_value": "[Petty Cash System]",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SYSTEM_EMAIL_FROM",
                "display_name": "System Email (From Address)",
                "description": "Email address used for system notifications",
                "category": "email",
                "setting_type": "email",
                "value": "noreply@pettycash.local",
                "default_value": "noreply@pettycash.local",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "EMAIL_BACKEND",
                "display_name": "Email Backend",
                "description": "Django email backend class (e.g., smtp, console, file)",
                "category": "email",
                "setting_type": "string",
                "value": "django.core.mail.backends.smtp.EmailBackend",
                "default_value": "django.core.mail.backends.smtp.EmailBackend",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": True,
            },
            {
                "key": "EMAIL_HOST",
                "display_name": "SMTP Host",
                "description": "SMTP server hostname",
                "category": "email",
                "setting_type": "string",
                "value": "smtp.gmail.com",
                "default_value": "smtp.gmail.com",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": True,
            },
            {
                "key": "EMAIL_PORT",
                "display_name": "SMTP Port",
                "description": "SMTP server port (587 for TLS, 465 for SSL, 25 for plain)",
                "category": "email",
                "setting_type": "integer",
                "value": "587",
                "default_value": "587",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": True,
            },
            {
                "key": "EMAIL_USE_TLS",
                "display_name": "Use TLS",
                "description": "Use TLS encryption for SMTP connection",
                "category": "email",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": True,
            },
            {
                "key": "EMAIL_USE_SSL",
                "display_name": "Use SSL",
                "description": "Use SSL encryption for SMTP connection",
                "category": "email",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": True,
            },
            {
                "key": "EMAIL_HOST_USER",
                "display_name": "SMTP Username",
                "description": "SMTP authentication username",
                "category": "email",
                "setting_type": "string",
                "value": "",
                "default_value": "",
                "is_sensitive": True,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": True,
            },
            {
                "key": "EMAIL_HOST_PASSWORD",
                "display_name": "SMTP Password",
                "description": "SMTP authentication password",
                "category": "email",
                "setting_type": "string",
                "value": "",
                "default_value": "",
                "is_sensitive": True,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": True,
            },
            {
                "key": "EMAIL_TIMEOUT",
                "display_name": "Email Timeout (seconds)",
                "description": "Timeout for email operations",
                "category": "email",
                "setting_type": "integer",
                "value": "30",
                "default_value": "30",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": True,
            },
            # GENERAL SETTINGS
            {
                "key": "APP_VERSION",
                "display_name": "App Version",
                "description": "Current deployed git version",
                "category": "general",
                "setting_type": "string",
                "value": "359c827",
                "default_value": "359c827",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "CURRENCY_CODE",
                "display_name": "Default Currency Code",
                "description": "Default currency for all transactions (ISO 4217 code: KES, USD, EUR, GBP, etc.)",
                "category": "general",
                "setting_type": "string",
                "value": "KES",
                "default_value": "KES",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "CURRENCY_DECIMAL_PLACES",
                "display_name": "Currency Decimal Places",
                "description": "Number of decimal places to display for currency amounts",
                "category": "general",
                "setting_type": "integer",
                "value": "2",
                "default_value": "2",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "CURRENCY_DECIMAL_SEPARATOR",
                "display_name": "Decimal Separator",
                "description": "Character to use as decimal separator (e.g., period, comma)",
                "category": "general",
                "setting_type": "string",
                "value": ".",
                "default_value": ".",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "CURRENCY_SYMBOL",
                "display_name": "Currency Symbol",
                "description": "Symbol to display for currency (e.g., KSh, $, €, £)",
                "category": "general",
                "setting_type": "string",
                "value": "KSh",
                "default_value": "KSh",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "CURRENCY_SYMBOL_POSITION",
                "display_name": "Currency Symbol Position",
                "description": "Position of currency symbol: before or after amount",
                "category": "general",
                "setting_type": "string",
                "value": "before",
                "default_value": "before",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "CURRENCY_THOUSAND_SEPARATOR",
                "display_name": "Thousand Separator",
                "description": "Character to use as thousand separator (e.g., comma, period, space)",
                "category": "general",
                "setting_type": "string",
                "value": ",",
                "default_value": ",",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "DATE_FORMAT",
                "display_name": "Date Display Format",
                "description": "Date format for display throughout the system",
                "category": "general",
                "setting_type": "string",
                "value": "Y-m-d",
                "default_value": "Y-m-d",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ENABLE_MULTI_CURRENCY",
                "display_name": "Enable Multi-Currency Support",
                "description": "Allow transactions in multiple currencies with exchange rates",
                "category": "general",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "EXCHANGE_RATE_API_KEY",
                "display_name": "Exchange Rate API Key",
                "description": "API key for exchange rate service (e.g., exchangerate-api.com)",
                "category": "general",
                "setting_type": "string",
                "value": "",
                "default_value": "",
                "is_sensitive": True,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "EXCHANGE_RATE_AUTO_UPDATE",
                "display_name": "Auto-Update Exchange Rates",
                "description": "Automatically update exchange rates from external API",
                "category": "general",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "MAINTENANCE_WINDOW_DURATION_MINUTES",
                "display_name": "Maintenance Window Duration (Minutes)",
                "description": "Default duration in minutes for maintenance windows",
                "category": "general",
                "setting_type": "integer",
                "value": "30",
                "default_value": "30",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAGINATION_PAGE_SIZE",
                "display_name": "Items Per Page",
                "description": "Number of items to display per page in lists",
                "category": "general",
                "setting_type": "integer",
                "value": "25",
                "default_value": "25",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SYSTEM_MAINTENANCE_MODE",
                "display_name": "Maintenance Mode",
                "description": "Enable maintenance mode (blocks non-admin access)",
                "category": "general",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            # NOTIFICATIONS SETTINGS
            {
                "key": "APPROVAL_EMAIL_NOTIFICATIONS",
                "display_name": "Send Email Notifications for Approvals",
                "description": "Enable/disable email notifications for approval actions",
                "category": "notifications",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "APPROVAL_ESCALATION_ALERT_RECIPIENTS",
                "display_name": "Approval Escalation Alert Recipients",
                "description": "Comma-separated emails for escalation alerts.",
                "category": "notifications",
                "setting_type": "string",
                "value": "",
                "default_value": "",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "APPROVAL_ESCALATION_EMAIL_NOTIFICATIONS",
                "display_name": "Send Email on Approval Escalation",
                "description": "Enable/disable email when approval is auto-escalated.",
                "category": "notifications",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "CRITICAL_OVERDUE_ALERT_RECIPIENTS",
                "display_name": "Critical Overdue Alert Recipients",
                "description": "Comma-separated emails for critical overdue alerts.",
                "category": "notifications",
                "setting_type": "string",
                "value": "",
                "default_value": "",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "DAILY_SUMMARY_EMAILS",
                "display_name": "Send Daily Summary Emails",
                "description": "Send daily summary of pending actions to approvers",
                "category": "notifications",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAYMENT_EMAIL_NOTIFICATIONS",
                "display_name": "Send Payment Confirmation Emails",
                "description": "Send email notifications when payments are executed",
                "category": "notifications",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REJECTION_EMAIL_NOTIFICATIONS",
                "display_name": "Send Rejection Notifications",
                "description": "Email users when their requisitions are rejected",
                "category": "notifications",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SEND_CRITICAL_OVERDUE_ALERTS",
                "display_name": "Send Critical Overdue Alerts",
                "description": "Enable/disable critical overdue alerts.",
                "category": "notifications",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SLA_BREACH_ALERT_RECIPIENTS",
                "display_name": "SLA Breach Alert Recipients",
                "description": "Comma-separated emails for SLA breach alerts.",
                "category": "notifications",
                "setting_type": "string",
                "value": "",
                "default_value": "",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SLA_BREACH_EMAIL_NOTIFICATIONS",
                "display_name": "Send Email on SLA Breach",
                "description": "Enable/disable email when SLA is breached.",
                "category": "notifications",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SLACK_NOTIFICATIONS_ENABLED",
                "display_name": "Enable Slack/Teams Notifications",
                "description": "Enable/disable Slack/Teams notifications.",
                "category": "notifications",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SMS_NOTIFICATIONS_ENABLED",
                "display_name": "Enable SMS Notifications",
                "description": "Enable/disable SMS notifications.",
                "category": "notifications",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SYSTEM_MAINTENANCE_ALERT_RECIPIENTS",
                "display_name": "System Maintenance Alert Recipients",
                "description": "Comma-separated emails for maintenance alerts.",
                "category": "notifications",
                "setting_type": "string",
                "value": "",
                "default_value": "",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SYSTEM_MAINTENANCE_EMAIL_NOTIFICATIONS",
                "display_name": "Send System Maintenance Emails",
                "description": "Enable/disable system maintenance emails.",
                "category": "notifications",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "WEBHOOK_NOTIFICATIONS_ENABLED",
                "display_name": "Enable Webhook Notifications",
                "description": "Enable/disable webhook notifications.",
                "category": "notifications",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            # ORGANIZATION SETTINGS
            {
                "key": "ALLOW_USER_SELF_REGISTRATION",
                "display_name": "Allow User Self-Registration",
                "description": "Enable users to register accounts themselves (requires admin approval)",
                "category": "organization",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ALLOWED_USER_ROLES",
                "display_name": "Allowed User Roles",
                "description": "Comma-separated list of roles that can be assigned",
                "category": "organization",
                "setting_type": "string",
                "value": "requester,department_head,group_finance_manager,cfo,ceo,treasury,fp&a,admin",
                "default_value": "requester,department_head,group_finance_manager,cfo,ceo,treasury,fp&a,admin",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "AUTO_DEACTIVATE_INACTIVE_DAYS",
                "display_name": "Auto-Deactivate After Inactivity (Days)",
                "description": "Automatically deactivate users after N days of inactivity (0 to disable)",
                "category": "organization",
                "setting_type": "integer",
                "value": "90",
                "default_value": "90",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "CONCURRENT_SESSIONS_ALLOWED",
                "display_name": "Concurrent Sessions Per User",
                "description": "Number of concurrent logins allowed (0 for unlimited)",
                "category": "organization",
                "setting_type": "integer",
                "value": "1",
                "default_value": "1",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "DEFAULT_USER_ROLE",
                "display_name": "Default User Role",
                "description": "Default role assigned to new users",
                "category": "organization",
                "setting_type": "string",
                "value": "requester",
                "default_value": "requester",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "DEPARTMENT_CREATION_RESTRICTED",
                "display_name": "Restrict Department Creation",
                "description": "Only admins can create new departments",
                "category": "organization",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "DISPLAY_USER_HIERARCHY",
                "display_name": "Display User Hierarchy",
                "description": "Show organizational chart/hierarchy in user interface",
                "category": "organization",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ENABLE_USER_DELEGATION",
                "display_name": "Enable User Delegation",
                "description": "Allow users to delegate their tasks when on leave",
                "category": "organization",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ENFORCE_DEPARTMENT_HIERARCHY",
                "display_name": "Enforce Department Hierarchy",
                "description": "Restrict access based on department reporting structure",
                "category": "organization",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "MAX_USERS_PER_DEPARTMENT",
                "display_name": "Max Users Per Department",
                "description": "Maximum number of users allowed per department (0 for unlimited)",
                "category": "organization",
                "setting_type": "integer",
                "value": "0",
                "default_value": "0",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "MULTI_DEPARTMENT_ACCESS",
                "display_name": "Allow Multi-Department Access",
                "description": "Allow users to belong to multiple departments",
                "category": "organization",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REQUIRE_EMAIL_VERIFICATION",
                "display_name": "Require Email Verification",
                "description": "Users must verify email before accessing the system",
                "category": "organization",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ROLE_CHANGE_REQUIRES_APPROVAL",
                "display_name": "Role Change Requires Approval",
                "description": "Role changes must be approved by admin/superuser",
                "category": "organization",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TRACK_USER_LOGIN_HISTORY",
                "display_name": "Track User Login History",
                "description": "Maintain log of user login times and IP addresses",
                "category": "organization",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "USER_PROFILE_FIELDS_REQUIRED",
                "display_name": "Required User Profile Fields",
                "description": "Comma-separated fields required in user profile (e.g., phone,employee_id)",
                "category": "organization",
                "setting_type": "string",
                "value": "email,first_name,last_name,department",
                "default_value": "email,first_name,last_name,department",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            # PAYMENT SETTINGS
            {
                "key": "MAX_PAYMENT_AMOUNT_WITHOUT_CEO",
                "display_name": "Max Payment Amount Without CEO",
                "description": "Maximum payment amount that can be processed without CEO approval",
                "category": "payment",
                "setting_type": "integer",
                "value": "1000000",
                "default_value": "1000000",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "MAX_PAYMENT_AMOUNT_WITHOUT_CFO",
                "display_name": "Max Payment Amount Without CFO",
                "description": "Maximum payment amount that can be processed without CFO approval",
                "category": "payment",
                "setting_type": "integer",
                "value": "500000",
                "default_value": "500000",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAYMENT_APPROVAL_REQUIRED",
                "display_name": "Payment Approval Required",
                "description": "Require treasury approval before executing payments",
                "category": "payment",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAYMENT_BATCH_PROCESSING",
                "display_name": "Enable Batch Payment Processing",
                "description": "Allow multiple payments to be processed at once",
                "category": "payment",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAYMENT_HOLD_ENABLED",
                "display_name": "Payment Hold Enabled",
                "description": "Allow payments to be placed on hold for manual review.",
                "category": "payment",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAYMENT_METHOD_RESTRICTIONS",
                "display_name": "Payment Method Restrictions",
                "description": "Restrict payment methods by amount or role (JSON config).",
                "category": "payment",
                "setting_type": "json",
                "value": '{"mpesa": {"max": 100000}, "bank": {"min": 10000}}',
                "default_value": '{"mpesa": {"max": 100000}, "bank": {"min": 10000}}',
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAYMENT_MULTI_APPROVAL_ENABLED",
                "display_name": "Multi-level Approval Enabled",
                "description": "Require multiple approvers for high-value payments.",
                "category": "payment",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAYMENT_NOTIFICATION_RECIPIENTS",
                "display_name": "Payment Notification Recipients",
                "description": "Comma-separated emails to notify on payment events.",
                "category": "payment",
                "setting_type": "string",
                "value": "",
                "default_value": "",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAYMENT_RECEIPT_REQUIRED",
                "display_name": "Payment Receipt Required",
                "description": "Require receipt upload before payment execution",
                "category": "payment",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAYMENT_TIME_WINDOW",
                "display_name": "Payment Time Window",
                "description": "Allowed payment hours (e.g., 08:00-18:00).",
                "category": "payment",
                "setting_type": "string",
                "value": "08:00-18:00",
                "default_value": "08:00-18:00",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            # REPORTING SETTINGS
            {
                "key": "AUTO_GENERATE_MONTHLY_REPORTS",
                "display_name": "Auto-Generate Monthly Reports",
                "description": "Automatically generate reports at end of each month",
                "category": "reporting",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ENABLE_REPORT_AUDIT_TRAIL",
                "display_name": "Enable Report Audit Trail",
                "description": "Log all report generation, export, and access events",
                "category": "reporting",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "FINANCIAL_YEAR_START_MONTH",
                "display_name": "Financial Year Start Month",
                "description": "Month when financial year starts (1-12, where 1=January)",
                "category": "reporting",
                "setting_type": "integer",
                "value": "1",
                "default_value": "1",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REPORT_ACCESS_ROLES",
                "display_name": "Report Access Roles",
                "description": "Roles allowed to view/download reports (comma-separated)",
                "category": "reporting",
                "setting_type": "string",
                "value": "admin,finance,manager",
                "default_value": "admin,finance,manager",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REPORT_DATA_MASKING",
                "display_name": "Enable Report Data Masking",
                "description": "Mask sensitive fields in exported reports for non-privileged users",
                "category": "reporting",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REPORT_EMAIL_RECIPIENTS",
                "display_name": "Report Email Recipients",
                "description": "Email addresses to receive auto-generated reports (comma-separated)",
                "category": "reporting",
                "setting_type": "string",
                "value": "finance@company.local",
                "default_value": "finance@company.local",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REPORT_EXPORT_FORMATS",
                "display_name": "Report Export Formats",
                "description": "Allowed export formats for reports (comma-separated: pdf,excel,csv)",
                "category": "reporting",
                "setting_type": "string",
                "value": "pdf,excel,csv",
                "default_value": "pdf,excel,csv",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REPORT_KPI_LIST",
                "display_name": "Report KPI List",
                "description": "List of KPIs to include in dashboard/stat cards (comma-separated)",
                "category": "reporting",
                "setting_type": "string",
                "value": "total_amount,avg_amount,approval_rate,payment_success_rate",
                "default_value": "total_amount,avg_amount,approval_rate,payment_success_rate",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REPORT_PRIVACY_LEVEL",
                "display_name": "Default Report Privacy Level",
                "description": "Default privacy level for generated reports (public, restricted, confidential)",
                "category": "reporting",
                "setting_type": "string",
                "value": "restricted",
                "default_value": "restricted",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REPORT_RETENTION_MONTHS",
                "display_name": "Report Retention Period (Months)",
                "description": "Number of months to keep generated reports",
                "category": "reporting",
                "setting_type": "integer",
                "value": "24",
                "default_value": "24",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REPORT_SCHEDULING_ENABLED",
                "display_name": "Enable Report Scheduling",
                "description": "Allow users/admins to schedule recurring reports",
                "category": "reporting",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REPORT_TEMPLATE_CHOICES",
                "display_name": "Report Template Choices",
                "description": "Available templates for report generation (comma-separated)",
                "category": "reporting",
                "setting_type": "string",
                "value": "default,summary,detailed",
                "default_value": "default,summary,detailed",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REPORT_TIMEZONE",
                "display_name": "Report Timezone",
                "description": "Timezone for report timestamps and scheduling",
                "category": "reporting",
                "setting_type": "string",
                "value": "Africa/Nairobi",
                "default_value": "Africa/Nairobi",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            # REQUISITION SETTINGS
            {
                "key": "ALLOW_DRAFT_REQUISITIONS",
                "display_name": "Allow Draft Requisitions",
                "description": "Enable users to save requisitions as drafts",
                "category": "requisition",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ALLOWED_ATTACHMENT_TYPES",
                "display_name": "Allowed Attachment Types",
                "description": "Allowed file extensions for attachments (comma-separated)",
                "category": "requisition",
                "setting_type": "string",
                "value": "pdf,jpg,jpeg,png,doc,docx,xls,xlsx",
                "default_value": "pdf,jpg,jpeg,png,doc,docx,xls,xlsx",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ATTACHMENT_MAX_SIZE_MB",
                "display_name": "Max Attachment Size (MB)",
                "description": "Maximum file size for attachments in megabytes",
                "category": "requisition",
                "setting_type": "integer",
                "value": "5",
                "default_value": "5",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "AUTO_SAVE_DRAFT_INTERVAL",
                "display_name": "Auto-Save Draft Interval (Seconds)",
                "description": "Automatically save draft every N seconds (0 to disable)",
                "category": "requisition",
                "setting_type": "integer",
                "value": "60",
                "default_value": "60",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "MINIMUM_REQUISITION_AMOUNT",
                "display_name": "Minimum Requisition Amount",
                "description": "Minimum amount allowed for a requisition",
                "category": "requisition",
                "setting_type": "integer",
                "value": "100",
                "default_value": "100",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REQUISITION_EDIT_AFTER_SUBMIT",
                "display_name": "Allow Edit After Submit",
                "description": "Allow requesters to edit submitted requisitions before approval",
                "category": "requisition",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REQUISITION_NUMBER_PREFIX",
                "display_name": "Requisition Number Prefix",
                "description": "Prefix for requisition numbers (e.g., REQ, PC)",
                "category": "requisition",
                "setting_type": "string",
                "value": "REQ",
                "default_value": "REQ",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            # SECURITY SETTINGS
            {
                "key": "ACCOUNT_LOCKOUT_DURATION_MINUTES",
                "display_name": "Account Lockout Duration (Minutes)",
                "description": "How long account remains locked after max failed login attempts",
                "category": "security",
                "setting_type": "integer",
                "value": "30",
                "default_value": "30",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ACTIVITY_LOG_RETENTION_DAYS",
                "display_name": "Activity Log Retention (Days)",
                "description": "Number of days to keep activity logs before archiving (minimum 365 for audit compliance)",
                "category": "security",
                "setting_type": "integer",
                "value": "365",
                "default_value": "365",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ALERT_MULTIPLE_CONCURRENT_SESSIONS",
                "display_name": "Alert on Multiple Sessions",
                "description": "Alert when user has multiple active sessions from different locations",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ALERT_RAPID_TRANSACTIONS",
                "display_name": "Alert on Rapid Multiple Transactions",
                "description": "Flag when user creates multiple transactions in short time",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ALERT_UNUSUAL_LOCATION",
                "display_name": "Alert on Unusual Location Login",
                "description": "Send alert when user logs in from new geographic location",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ALERT_UNUSUAL_TIME",
                "display_name": "Alert on Off-Hours Access",
                "description": "Send alert when user accesses system outside business hours",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ALLOWED_IP_ADDRESSES",
                "display_name": "Allowed IP Addresses",
                "description": "Comma-separated list of allowed IPs (e.g., 192.168.1.0/24, 10.0.0.1)",
                "category": "security",
                "setting_type": "string",
                "value": "",
                "default_value": "",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "AUTO_LOGOUT_ON_BROWSER_CLOSE",
                "display_name": "Auto Logout on Browser Close",
                "description": "Automatically end session when browser is closed",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "BUSINESS_HOURS_END",
                "display_name": "Business Hours End Time",
                "description": "End of normal business hours (24-hour format, e.g., 18:00)",
                "category": "security",
                "setting_type": "string",
                "value": "18:00",
                "default_value": "18:00",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "BUSINESS_HOURS_START",
                "display_name": "Business Hours Start Time",
                "description": "Start of normal business hours (24-hour format, e.g., 08:00)",
                "category": "security",
                "setting_type": "string",
                "value": "08:00",
                "default_value": "08:00",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ENABLE_ACTIVITY_GEOLOCATION",
                "display_name": "Enable Activity Location Tracking",
                "description": "Track geographic location of user activities using IP geolocation",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ENABLE_AUDIT_TRAIL_ENCRYPTION",
                "display_name": "Encrypt Sensitive Audit Data",
                "description": "Encrypt sensitive fields in activity logs and audit trails",
                "category": "security",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ENABLE_DATA_MASKING",
                "display_name": "Enable Data Masking",
                "description": "Mask sensitive financial data in logs and non-privileged views",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ENABLE_FRAUD_DETECTION",
                "display_name": "Enable Fraud Detection",
                "description": "Monitor for suspicious transaction patterns and anomalies",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ENABLE_IP_WHITELIST",
                "display_name": "Enable IP Address Whitelist",
                "description": "Restrict access to approved IP addresses only",
                "category": "security",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ENABLE_TRANSACTION_SIGNING",
                "display_name": "Enable Digital Transaction Signing",
                "description": "Require digital signature for high-value transactions",
                "category": "security",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ENABLE_TWO_FACTOR_AUTH",
                "display_name": "Enable Two-Factor Authentication",
                "description": "Require 2FA for all users or high-value transactions",
                "category": "security",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "ENFORCE_DEVICE_WHITELIST",
                "display_name": "Enforce Device Whitelisting",
                "description": "Only allow login from whitelisted devices (users must request new devices)",
                "category": "security",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "FORCE_HTTPS",
                "display_name": "Force HTTPS",
                "description": "Require all requests to use HTTPS.",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "FRAUD_ALERT_EMAIL_NOTIFICATIONS",
                "display_name": "Send Fraud Detection Emails",
                "description": "Enable/disable fraud detection emails.",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "FRAUD_ALERT_RECIPIENTS",
                "display_name": "Fraud Alert Recipients",
                "description": "Comma-separated emails for fraud alerts.",
                "category": "security",
                "setting_type": "string",
                "value": "",
                "default_value": "",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "INVITATION_EXPIRY_DAYS",
                "display_name": "User Invitation Expiry (Days)",
                "description": "Number of days before invitation links expire",
                "category": "security",
                "setting_type": "integer",
                "value": "7",
                "default_value": "7",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "LOGIN_NOTIFICATION_ENABLED",
                "display_name": "Login Notification Enabled",
                "description": "Send notification on successful or failed login.",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "MAX_LOGIN_ATTEMPTS",
                "display_name": "Maximum Login Attempts",
                "description": "Maximum failed login attempts before account lockout",
                "category": "security",
                "setting_type": "integer",
                "value": "5",
                "default_value": "5",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "MIN_PASSWORD_LENGTH",
                "display_name": "Minimum Password Length",
                "description": "Minimum number of characters required in passwords",
                "category": "security",
                "setting_type": "integer",
                "value": "12",
                "default_value": "12",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PASSWORD_EXPIRY_DAYS",
                "display_name": "Password Expiry (Days)",
                "description": "Number of days before a password must be changed.",
                "category": "security",
                "setting_type": "integer",
                "value": "90",
                "default_value": "90",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PASSWORD_RESET_TIMEOUT_DAYS",
                "display_name": "Password Reset Link Validity (Days)",
                "description": "Number of days password reset links remain valid",
                "category": "security",
                "setting_type": "integer",
                "value": "1",
                "default_value": "1",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAYMENT_OTP_EXPIRY_MINUTES",
                "display_name": "Payment OTP Expiry (Minutes)",
                "description": "Number of minutes before OTP expires for payment authentication",
                "category": "security",
                "setting_type": "integer",
                "value": "5",
                "default_value": "5",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PREVENT_PASSWORD_REUSE",
                "display_name": "Prevent Password Reuse (Last N)",
                "description": "Number of previous passwords that cannot be reused (0 to disable)",
                "category": "security",
                "setting_type": "integer",
                "value": "5",
                "default_value": "5",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "RAPID_TRANSACTION_THRESHOLD",
                "display_name": "Rapid Transaction Threshold",
                "description": "Number of transactions within threshold minutes considered suspicious",
                "category": "security",
                "setting_type": "integer",
                "value": "5",
                "default_value": "5",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "RAPID_TRANSACTION_WINDOW_MINUTES",
                "display_name": "Rapid Transaction Window (Minutes)",
                "description": "Time window for detecting rapid transactions",
                "category": "security",
                "setting_type": "integer",
                "value": "10",
                "default_value": "10",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "RATE_LIMIT_LOGIN_ATTEMPTS",
                "display_name": "Rate Limit Login Attempts",
                "description": "Maximum login attempts per IP/device per hour.",
                "category": "security",
                "setting_type": "integer",
                "value": "20",
                "default_value": "20",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REQUIRE_2FA_ABOVE_AMOUNT",
                "display_name": "2FA Required Above Amount",
                "description": "Require 2FA for transactions above this amount (0 to disable)",
                "category": "security",
                "setting_type": "integer",
                "value": "100000",
                "default_value": "100000",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REQUIRE_2FA_FOR_APPROVERS",
                "display_name": "Mandatory 2FA for Approvers",
                "description": "Force 2FA for users with approval privileges",
                "category": "security",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REQUIRE_PASSWORD_CHANGE_DAYS",
                "display_name": "Force Password Change After (Days)",
                "description": "Require users to change password periodically (0 to disable, recommended: 90)",
                "category": "security",
                "setting_type": "integer",
                "value": "90",
                "default_value": "90",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "REQUIRE_PASSWORD_COMPLEXITY",
                "display_name": "Require Strong Password Complexity",
                "description": "Enforce uppercase, lowercase, numbers, and special characters",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SECURITY_ALERT_EMAIL_NOTIFICATIONS",
                "display_name": "Send Security Incident Emails",
                "description": "Enable/disable security incident emails.",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SECURITY_ALERT_RECIPIENTS",
                "display_name": "Security Alert Email Recipients",
                "description": "Comma-separated emails for security alerts",
                "category": "security",
                "setting_type": "string",
                "value": "security@company.com,admin@company.com",
                "default_value": "security@company.com",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SECURITY_LOCKOUT_DURATION_MINUTES",
                "display_name": "",
                "description": "How long to lock out account after threshold is reached (minutes)",
                "category": "security",
                "setting_type": "integer",
                "value": "30",
                "default_value": "",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SECURITY_LOCKOUT_THRESHOLD",
                "display_name": "Lockout Threshold (failed attempts)",
                "description": "Number of failed login attempts before an account is temporarily locked.",
                "category": "security",
                "setting_type": "integer",
                "value": "5",
                "default_value": "5",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SECURITY_LOCKOUT_WINDOW_MINUTES",
                "display_name": "Lockout Window (minutes)",
                "description": "How long an account remains locked after too many failed attempts.",
                "category": "security",
                "setting_type": "integer",
                "value": "15",
                "default_value": "15",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SECURITY_SINGLE_SESSION_ENFORCED",
                "display_name": "Enforce Single Session Per User",
                "description": "When enabled, logging in from a new device/browser terminates all other active sessions for that user.",
                "category": "security",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SESSION_TIMEOUT_MINUTES",
                "display_name": "Session Timeout (Minutes)",
                "description": "Auto logout after inactivity (recommended: 15-30 minutes for financial systems)",
                "category": "security",
                "setting_type": "integer",
                "value": "30",
                "default_value": "30",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TRANSACTION_SIGNING_THRESHOLD",
                "display_name": "Transaction Signing Threshold",
                "description": "Amount above which digital signature is required",
                "category": "security",
                "setting_type": "integer",
                "value": "500000",
                "default_value": "500000",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            # TREASURY SETTINGS
            {
                "key": "ENABLE_VARIANCE_TRACKING",
                "display_name": "Enable Variance Tracking",
                "description": "Track and report variances between expected and actual amounts",
                "category": "treasury",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "LOW_BALANCE_ALERT_THRESHOLD",
                "display_name": "Low Balance Alert Threshold",
                "description": "Send alert when petty cash balance falls below this amount",
                "category": "treasury",
                "setting_type": "integer",
                "value": "50000",
                "default_value": "50000",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAYMENT_EXECUTION_TIMEOUT_MINUTES",
                "display_name": "Payment Execution Timeout (Minutes)",
                "description": "Maximum minutes allowed for payment execution before triggering timeout alert",
                "category": "treasury",
                "setting_type": "integer",
                "value": "60",
                "default_value": "60",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAYMENT_METHODS_ALLOWED",
                "display_name": "Payment Methods Allowed",
                "description": "Allowed payment methods (comma-separated: cash,bank_transfer,mobile_money,cheque)",
                "category": "treasury",
                "setting_type": "string",
                "value": "cash,bank_transfer,mobile_money",
                "default_value": "cash,bank_transfer,mobile_money",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "RECONCILIATION_FREQUENCY_DAYS",
                "display_name": "Reconciliation Frequency (Days)",
                "description": "How often reconciliation should be performed",
                "category": "treasury",
                "setting_type": "integer",
                "value": "7",
                "default_value": "7",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TREASURY_ALLOW_NEGATIVE_BALANCE",
                "display_name": "Allow Negative Fund Balance",
                "description": "Whether treasury funds can have negative balances (overdraft). If disabled, payments will be rejected when insufficient funds.",
                "category": "treasury",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TREASURY_AUTO_REPLENISHMENT_ENABLED",
                "display_name": "Enable Auto Replenishment Requests",
                "description": "Automatically create replenishment requests when fund balance falls below reorder level.",
                "category": "treasury",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TREASURY_DEFAULT_REORDER_LEVEL",
                "display_name": "Default Fund Reorder Level",
                "description": "Default minimum balance threshold for treasury funds. When fund balance falls below this, system alerts for replenishment.",
                "category": "treasury",
                "setting_type": "integer",
                "value": "50000",
                "default_value": "50000",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TREASURY_DEFAULT_REPLENISHMENT_AMOUNT",
                "display_name": "Default Replenishment Amount",
                "description": "Default amount to replenish when creating manual replenishment requests.",
                "category": "treasury",
                "setting_type": "integer",
                "value": "100000",
                "default_value": "100000",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TREASURY_FORECAST_HORIZON_DAYS",
                "display_name": "Treasury Forecast Horizon (Days)",
                "description": "Number of days to forecast ahead for treasury projections",
                "category": "treasury",
                "setting_type": "integer",
                "value": "30",
                "default_value": "30",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TREASURY_HISTORY_LOOKBACK_DAYS",
                "display_name": "Treasury History Lookback (Days)",
                "description": "Number of days to look back for historical treasury analysis",
                "category": "treasury",
                "setting_type": "integer",
                "value": "30",
                "default_value": "30",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TREASURY_LOW_BALANCE_ALERT_PERCENTAGE",
                "display_name": "Low Balance Alert Percentage",
                "description": "Percentage of reorder level at which to send low balance alerts. E.g., 80 means alert when balance is 80% of reorder level.",
                "category": "treasury",
                "setting_type": "integer",
                "value": "100",
                "default_value": "100",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TREASURY_MAX_PAYMENT_RETRY_ATTEMPTS",
                "display_name": "Maximum Payment Retry Attempts",
                "description": "Maximum number of times a failed payment can be retried.",
                "category": "treasury",
                "setting_type": "integer",
                "value": "3",
                "default_value": "3",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TREASURY_MINIMUM_FUND_BALANCE",
                "display_name": "Minimum Fund Balance",
                "description": "Minimum allowed balance for treasury funds. Prevents fund balance from going below this amount.",
                "category": "treasury",
                "setting_type": "integer",
                "value": "0",
                "default_value": "0",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TREASURY_OTP_EXPIRY_MINUTES",
                "display_name": "OTP Expiry Time (minutes)",
                "description": "How long OTP codes remain valid for payment verification.",
                "category": "treasury",
                "setting_type": "integer",
                "value": "5",
                "default_value": "5",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TREASURY_PAYMENT_EXECUTION_TIMEOUT",
                "display_name": "Payment Execution Timeout (seconds)",
                "description": "Maximum time allowed for payment execution before timeout.",
                "category": "treasury",
                "setting_type": "integer",
                "value": "300",
                "default_value": "300",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TREASURY_REQUIRE_OTP_FOR_PAYMENTS",
                "display_name": "Require OTP for Payments",
                "description": "Require OTP verification for all payment executions for additional security.",
                "category": "treasury",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "VARIANCE_APPROVAL_DEADLINE_HOURS",
                "display_name": "Variance Approval Deadline (Hours)",
                "description": "Maximum hours before variance approval request triggers timeout alert",
                "category": "treasury",
                "setting_type": "integer",
                "value": "24",
                "default_value": "24",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "VARIANCE_TOLERANCE_PERCENTAGE",
                "display_name": "Variance Tolerance (%)",
                "description": "Acceptable variance percentage before flagging",
                "category": "treasury",
                "setting_type": "integer",
                "value": "5",
                "default_value": "5",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            # WORKFLOW SETTINGS
            {
                "key": "APPROVAL_REMINDER_FREQUENCY_HOURS",
                "display_name": "Approval Reminder Frequency (Hours)",
                "description": "Send reminder to approvers every N hours for pending items",
                "category": "workflow",
                "setting_type": "integer",
                "value": "24",
                "default_value": "24",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "APPROVAL_SLA_HOURS",
                "display_name": "Approval SLA (Hours)",
                "description": "Target turnaround time for approval actions",
                "category": "workflow",
                "setting_type": "integer",
                "value": "48",
                "default_value": "48",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "AUTO_APPROVE_BELOW_THRESHOLD",
                "display_name": "Auto-Approve Below Threshold",
                "description": "Automatically approve requisitions below minimum amount (risky)",
                "category": "workflow",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "AUTO_ESCALATE_AFTER_DAYS",
                "display_name": "Auto-Escalate After Days",
                "description": "Auto-escalate to next level if no action after N days (0 to disable)",
                "category": "workflow",
                "setting_type": "integer",
                "value": "3",
                "default_value": "3",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "BUSINESS_HOURS_ONLY",
                "display_name": "Business Hours Only",
                "description": "Restrict workflow actions to business hours (9 AM - 5 PM)",
                "category": "workflow",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "CRITICAL_OVERDUE_HOURS",
                "display_name": "Critical Overdue Threshold (Hours)",
                "description": "Flag as critical/urgent when overdue exceeds this threshold",
                "category": "workflow",
                "setting_type": "integer",
                "value": "120",
                "default_value": "120",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "DELEGATE_APPROVALS_ENABLED",
                "display_name": "Enable Approval Delegation",
                "description": "Allow approvers to delegate their authority to others",
                "category": "workflow",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "END_TO_END_SLA_DAYS",
                "display_name": "End-to-End SLA (Days)",
                "description": "Total target time from requisition submission to payment",
                "category": "workflow",
                "setting_type": "integer",
                "value": "5",
                "default_value": "5",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "OVERDUE_ALERT_RECIPIENTS",
                "display_name": "Overdue Alert Recipients",
                "description": "Additional recipients for overdue alerts (comma-separated emails)",
                "category": "workflow",
                "setting_type": "string",
                "value": "admin@company.local",
                "default_value": "admin@company.local",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "OVERDUE_THRESHOLD_HOURS",
                "display_name": "Overdue Threshold (Hours)",
                "description": "Mark requisition as overdue after N hours without action",
                "category": "workflow",
                "setting_type": "integer",
                "value": "72",
                "default_value": "72",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PARALLEL_APPROVALS_ENABLED",
                "display_name": "Enable Parallel Approvals",
                "description": "Allow multiple approvers at same level to approve simultaneously",
                "category": "workflow",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "PAYMENT_SLA_HOURS",
                "display_name": "Payment SLA (Hours)",
                "description": "Target turnaround time for payment execution after approval",
                "category": "workflow",
                "setting_type": "integer",
                "value": "24",
                "default_value": "24",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "SEND_OVERDUE_ALERTS",
                "display_name": "Send Overdue Alerts",
                "description": "Send email alerts when requisitions become overdue",
                "category": "workflow",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "TRACK_WORKFLOW_METRICS",
                "display_name": "Track Workflow Metrics",
                "description": "Enable tracking of TAT, SLA compliance, and bottleneck analysis",
                "category": "workflow",
                "setting_type": "boolean",
                "value": "true",
                "default_value": "true",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
            {
                "key": "WEEKEND_PROCESSING_ENABLED",
                "display_name": "Weekend Processing Enabled",
                "description": "Allow approvals and payments during weekends",
                "category": "workflow",
                "setting_type": "boolean",
                "value": "false",
                "default_value": "false",
                "is_sensitive": False,
                "is_active": True,
                "editable_by_admin": True,
                "requires_restart": False,
            },
        ]

        for setting_data in settings:
            setting, created = SystemSetting.objects.update_or_create(
                key=setting_data["key"], defaults=setting_data
            )
            if created:
                created_count += 1
                self.stdout.write(
                    self.style.SUCCESS(f"✓ Created: {setting.display_name}")
                )
            else:
                updated_count += 1
                self.stdout.write(f"  Updated: {setting.display_name}")

        self.stdout.write(
            self.style.SUCCESS(
                f"\n✓ Seeded {created_count} new settings, updated {updated_count} existing"
            )
        )

        # Summary by category
        category_counts = {}
        for setting in SystemSetting.objects.filter(is_active=True):
            category_counts[setting.category] = (
                category_counts.get(setting.category, 0) + 1
            )

        self.stdout.write("\nSettings by category:")
        for category, count in sorted(category_counts.items()):
            self.stdout.write(f"  {category.title()}: {count}")
