from django.core.management.base import BaseCommand
from settings_manager.models import SystemSetting


class Command(BaseCommand):
    help = 'Seed default system settings'

    def handle(self, *args, **options):
        settings = [
            # EMAIL SETTINGS
            {
                'key': 'SYSTEM_EMAIL_FROM',
                'display_name': 'System Email (From Address)',
                'description': 'Email address used for system notifications',
                'category': 'email',
                'setting_type': 'email',
                'value': 'noreply@pettycash.local',
                'default_value': 'noreply@pettycash.local',
            },
            {
                'key': 'EMAIL_REPLY_TO',
                'display_name': 'Email Reply-To Address',
                'description': 'Reply-to email address for system notifications',
                'category': 'email',
                'setting_type': 'email',
                'value': 'support@pettycash.local',
                'default_value': 'support@pettycash.local',
            },
            {
                'key': 'EMAIL_SUBJECT_PREFIX',
                'display_name': 'Email Subject Prefix',
                'description': 'Prefix added to all email subjects',
                'category': 'email',
                'setting_type': 'string',
                'value': '[Petty Cash System]',
                'default_value': '[Petty Cash System]',
            },
            
            # APPROVAL SETTINGS
            {
                'key': 'DEFAULT_CHANGE_REQUEST_DEADLINE_HOURS',
                'display_name': 'Default Change Request Deadline (Hours)',
                'description': 'Default number of hours for requester to respond to change requests',
                'category': 'approval',
                'setting_type': 'integer',
                'value': '48',
                'default_value': '48',
            },
            {
                'key': 'AUTO_REJECT_EXPIRED_CHANGES',
                'display_name': 'Auto-Reject Expired Change Requests',
                'description': 'Automatically reject requisitions when change request deadline expires',
                'category': 'approval',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'MAX_REQUISITION_AMOUNT',
                'display_name': 'Maximum Requisition Amount',
                'description': 'Maximum amount allowed for a single requisition',
                'category': 'approval',
                'setting_type': 'integer',
                'value': '1000000',
                'default_value': '1000000',
            },
            {
                'key': 'FAST_TRACK_ENABLED',
                'display_name': 'Enable Fast-Track Approvals',
                'description': 'Allow urgent requisitions to skip intermediate approvers',
                'category': 'approval',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'ALLOW_SELF_APPROVAL',
                'display_name': 'Allow Self-Approval',
                'description': 'Allow users to approve their own requisitions (Not recommended)',
                'category': 'approval',
                'setting_type': 'boolean',
                'value': 'false',
                'default_value': 'false',
            },
            
            # PAYMENT SETTINGS
            {
                'key': 'PAYMENT_APPROVAL_REQUIRED',
                'display_name': 'Payment Approval Required',
                'description': 'Require treasury approval before executing payments',
                'category': 'payment',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'MAX_PAYMENT_AMOUNT_WITHOUT_CFO',
                'display_name': 'Max Payment Amount Without CFO',
                'description': 'Maximum payment amount that can be processed without CFO approval',
                'category': 'payment',
                'setting_type': 'integer',
                'value': '500000',
                'default_value': '500000',
            },
            {
                'key': 'MAX_PAYMENT_AMOUNT_WITHOUT_CEO',
                'display_name': 'Max Payment Amount Without CEO',
                'description': 'Maximum payment amount that can be processed without CEO approval',
                'category': 'payment',
                'setting_type': 'integer',
                'value': '1000000',
                'default_value': '1000000',
            },
            {
                'key': 'PAYMENT_RECEIPT_REQUIRED',
                'display_name': 'Payment Receipt Required',
                'description': 'Require receipt upload before payment execution',
                'category': 'payment',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'PAYMENT_BATCH_PROCESSING',
                'display_name': 'Enable Batch Payment Processing',
                'description': 'Allow multiple payments to be processed at once',
                'category': 'payment',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            
            # SECURITY SETTINGS
            {
                'key': 'ACTIVITY_LOG_RETENTION_DAYS',
                'display_name': 'Activity Log Retention (Days)',
                'description': 'Number of days to keep activity logs before archiving',
                'category': 'security',
                'setting_type': 'integer',
                'value': '90',
                'default_value': '90',
            },
            {
                'key': 'SESSION_TIMEOUT_MINUTES',
                'display_name': 'Session Timeout (Minutes)',
                'description': 'User session timeout in minutes (0 for browser session)',
                'category': 'security',
                'setting_type': 'integer',
                'value': '60',
                'default_value': '60',
            },
            {
                'key': 'PASSWORD_RESET_TIMEOUT_DAYS',
                'display_name': 'Password Reset Link Validity (Days)',
                'description': 'Number of days password reset links remain valid',
                'category': 'security',
                'setting_type': 'integer',
                'value': '1',
                'default_value': '1',
            },
            {
                'key': 'MAX_LOGIN_ATTEMPTS',
                'display_name': 'Maximum Login Attempts',
                'description': 'Maximum failed login attempts before account lockout',
                'category': 'security',
                'setting_type': 'integer',
                'value': '5',
                'default_value': '5',
            },
            {
                'key': 'ENABLE_ACTIVITY_GEOLOCATION',
                'display_name': 'Enable Activity Location Tracking',
                'description': 'Track geographic location of user activities using IP geolocation',
                'category': 'security',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            
            # NOTIFICATION SETTINGS
            {
                'key': 'APPROVAL_EMAIL_NOTIFICATIONS',
                'display_name': 'Send Email Notifications for Approvals',
                'description': 'Enable/disable email notifications for approval actions',
                'category': 'notifications',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'PAYMENT_EMAIL_NOTIFICATIONS',
                'display_name': 'Send Payment Confirmation Emails',
                'description': 'Send email notifications when payments are executed',
                'category': 'notifications',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'REJECTION_EMAIL_NOTIFICATIONS',
                'display_name': 'Send Rejection Notifications',
                'description': 'Email users when their requisitions are rejected',
                'category': 'notifications',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'DAILY_SUMMARY_EMAILS',
                'display_name': 'Send Daily Summary Emails',
                'description': 'Send daily summary of pending actions to approvers',
                'category': 'notifications',
                'setting_type': 'boolean',
                'value': 'false',
                'default_value': 'false',
            },
            
            # GENERAL SETTINGS
            {
                'key': 'SYSTEM_MAINTENANCE_MODE',
                'display_name': 'Maintenance Mode',
                'description': 'Enable maintenance mode (blocks non-admin access)',
                'category': 'general',
                'setting_type': 'boolean',
                'value': 'false',
                'default_value': 'false',
            },
            {
                'key': 'CURRENCY_CODE',
                'display_name': 'Default Currency Code',
                'description': 'Default currency for all transactions (ISO 4217 code: KES, USD, EUR, GBP, etc.)',
                'category': 'general',
                'setting_type': 'string',
                'value': 'KES',
                'default_value': 'KES',
            },
            {
                'key': 'CURRENCY_SYMBOL',
                'display_name': 'Currency Symbol',
                'description': 'Symbol to display for currency (e.g., KSh, $, €, £)',
                'category': 'general',
                'setting_type': 'string',
                'value': 'KSh',
                'default_value': 'KSh',
            },
            {
                'key': 'CURRENCY_SYMBOL_POSITION',
                'display_name': 'Currency Symbol Position',
                'description': 'Position of currency symbol: before or after amount',
                'category': 'general',
                'setting_type': 'string',
                'value': 'before',
                'default_value': 'before',
            },
            {
                'key': 'CURRENCY_DECIMAL_PLACES',
                'display_name': 'Currency Decimal Places',
                'description': 'Number of decimal places to display for currency amounts',
                'category': 'general',
                'setting_type': 'integer',
                'value': '2',
                'default_value': '2',
            },
            {
                'key': 'CURRENCY_THOUSAND_SEPARATOR',
                'display_name': 'Thousand Separator',
                'description': 'Character to use as thousand separator (e.g., comma, period, space)',
                'category': 'general',
                'setting_type': 'string',
                'value': ',',
                'default_value': ',',
            },
            {
                'key': 'CURRENCY_DECIMAL_SEPARATOR',
                'display_name': 'Decimal Separator',
                'description': 'Character to use as decimal separator (e.g., period, comma)',
                'category': 'general',
                'setting_type': 'string',
                'value': '.',
                'default_value': '.',
            },
            {
                'key': 'ENABLE_MULTI_CURRENCY',
                'display_name': 'Enable Multi-Currency Support',
                'description': 'Allow transactions in multiple currencies with exchange rates',
                'category': 'general',
                'setting_type': 'boolean',
                'value': 'false',
                'default_value': 'false',
            },
            {
                'key': 'EXCHANGE_RATE_AUTO_UPDATE',
                'display_name': 'Auto-Update Exchange Rates',
                'description': 'Automatically update exchange rates from external API',
                'category': 'general',
                'setting_type': 'boolean',
                'value': 'false',
                'default_value': 'false',
            },
            {
                'key': 'EXCHANGE_RATE_API_KEY',
                'display_name': 'Exchange Rate API Key',
                'description': 'API key for exchange rate service (e.g., exchangerate-api.com)',
                'category': 'general',
                'setting_type': 'string',
                'value': '',
                'default_value': '',
                'is_sensitive': True,
            },
            {
                'key': 'DATE_FORMAT',
                'display_name': 'Date Display Format',
                'description': 'Date format for display throughout the system',
                'category': 'general',
                'setting_type': 'string',
                'value': 'Y-m-d',
                'default_value': 'Y-m-d',
            },
            {
                'key': 'PAGINATION_PAGE_SIZE',
                'display_name': 'Items Per Page',
                'description': 'Number of items to display per page in lists',
                'category': 'general',
                'setting_type': 'integer',
                'value': '25',
                'default_value': '25',
            },
            
            # REPORTING SETTINGS
            {
                'key': 'REPORT_EXPORT_FORMATS',
                'display_name': 'Report Export Formats',
                'description': 'Allowed export formats for reports (comma-separated: pdf,excel,csv)',
                'category': 'reporting',
                'setting_type': 'string',
                'value': 'pdf,excel,csv',
                'default_value': 'pdf,excel,csv',
            },
            {
                'key': 'AUTO_GENERATE_MONTHLY_REPORTS',
                'display_name': 'Auto-Generate Monthly Reports',
                'description': 'Automatically generate reports at end of each month',
                'category': 'reporting',
                'setting_type': 'boolean',
                'value': 'false',
                'default_value': 'false',
            },
            {
                'key': 'REPORT_EMAIL_RECIPIENTS',
                'display_name': 'Report Email Recipients',
                'description': 'Email addresses to receive auto-generated reports (comma-separated)',
                'category': 'reporting',
                'setting_type': 'string',
                'value': 'finance@company.local',
                'default_value': 'finance@company.local',
            },
            {
                'key': 'FINANCIAL_YEAR_START_MONTH',
                'display_name': 'Financial Year Start Month',
                'description': 'Month when financial year starts (1-12, where 1=January)',
                'category': 'reporting',
                'setting_type': 'integer',
                'value': '1',
                'default_value': '1',
            },
            {
                'key': 'REPORT_RETENTION_MONTHS',
                'display_name': 'Report Retention Period (Months)',
                'description': 'Number of months to keep generated reports',
                'category': 'reporting',
                'setting_type': 'integer',
                'value': '24',
                'default_value': '24',
            },
            
            # REQUISITION SETTINGS
            {
                'key': 'ALLOW_DRAFT_REQUISITIONS',
                'display_name': 'Allow Draft Requisitions',
                'description': 'Enable users to save requisitions as drafts',
                'category': 'requisition',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'AUTO_SAVE_DRAFT_INTERVAL',
                'display_name': 'Auto-Save Draft Interval (Seconds)',
                'description': 'Automatically save draft every N seconds (0 to disable)',
                'category': 'requisition',
                'setting_type': 'integer',
                'value': '60',
                'default_value': '60',
            },
            {
                'key': 'REQUISITION_NUMBER_PREFIX',
                'display_name': 'Requisition Number Prefix',
                'description': 'Prefix for requisition numbers (e.g., REQ, PC)',
                'category': 'requisition',
                'setting_type': 'string',
                'value': 'REQ',
                'default_value': 'REQ',
            },
            {
                'key': 'MINIMUM_REQUISITION_AMOUNT',
                'display_name': 'Minimum Requisition Amount',
                'description': 'Minimum amount allowed for a requisition',
                'category': 'requisition',
                'setting_type': 'integer',
                'value': '100',
                'default_value': '100',
            },
            {
                'key': 'ATTACHMENT_MAX_SIZE_MB',
                'display_name': 'Max Attachment Size (MB)',
                'description': 'Maximum file size for attachments in megabytes',
                'category': 'requisition',
                'setting_type': 'integer',
                'value': '5',
                'default_value': '5',
            },
            {
                'key': 'ALLOWED_ATTACHMENT_TYPES',
                'display_name': 'Allowed Attachment Types',
                'description': 'Allowed file extensions for attachments (comma-separated)',
                'category': 'requisition',
                'setting_type': 'string',
                'value': 'pdf,jpg,jpeg,png,doc,docx,xls,xlsx',
                'default_value': 'pdf,jpg,jpeg,png,doc,docx,xls,xlsx',
            },
            {
                'key': 'REQUISITION_EDIT_AFTER_SUBMIT',
                'display_name': 'Allow Edit After Submit',
                'description': 'Allow requesters to edit submitted requisitions before approval',
                'category': 'requisition',
                'setting_type': 'boolean',
                'value': 'false',
                'default_value': 'false',
            },
            
            # TREASURY SETTINGS
            {
                'key': 'LOW_BALANCE_ALERT_THRESHOLD',
                'display_name': 'Low Balance Alert Threshold',
                'description': 'Send alert when petty cash balance falls below this amount',
                'category': 'treasury',
                'setting_type': 'integer',
                'value': '50000',
                'default_value': '50000',
            },
            {
                'key': 'ENABLE_VARIANCE_TRACKING',
                'display_name': 'Enable Variance Tracking',
                'description': 'Track and report variances between expected and actual amounts',
                'category': 'treasury',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'VARIANCE_TOLERANCE_PERCENTAGE',
                'display_name': 'Variance Tolerance (%)',
                'description': 'Acceptable variance percentage before flagging',
                'category': 'treasury',
                'setting_type': 'integer',
                'value': '5',
                'default_value': '5',
            },
            {
                'key': 'PAYMENT_METHODS_ALLOWED',
                'display_name': 'Payment Methods Allowed',
                'description': 'Allowed payment methods (comma-separated: cash,bank_transfer,mobile_money,cheque)',
                'category': 'treasury',
                'setting_type': 'string',
                'value': 'cash,bank_transfer,mobile_money',
                'default_value': 'cash,bank_transfer,mobile_money',
            },
            {
                'key': 'RECONCILIATION_FREQUENCY_DAYS',
                'display_name': 'Reconciliation Frequency (Days)',
                'description': 'How often reconciliation should be performed',
                'category': 'treasury',
                'setting_type': 'integer',
                'value': '7',
                'default_value': '7',
            },
            
            # WORKFLOW SETTINGS
            {
                'key': 'APPROVAL_REMINDER_FREQUENCY_HOURS',
                'display_name': 'Approval Reminder Frequency (Hours)',
                'description': 'Send reminder to approvers every N hours for pending items',
                'category': 'workflow',
                'setting_type': 'integer',
                'value': '24',
                'default_value': '24',
            },
            {
                'key': 'AUTO_ESCALATE_AFTER_DAYS',
                'display_name': 'Auto-Escalate After Days',
                'description': 'Auto-escalate to next level if no action after N days (0 to disable)',
                'category': 'workflow',
                'setting_type': 'integer',
                'value': '3',
                'default_value': '3',
            },
            {
                'key': 'WEEKEND_PROCESSING_ENABLED',
                'display_name': 'Weekend Processing Enabled',
                'description': 'Allow approvals and payments during weekends',
                'category': 'workflow',
                'setting_type': 'boolean',
                'value': 'false',
                'default_value': 'false',
            },
            {
                'key': 'BUSINESS_HOURS_ONLY',
                'display_name': 'Business Hours Only',
                'description': 'Restrict workflow actions to business hours (9 AM - 5 PM)',
                'category': 'workflow',
                'setting_type': 'boolean',
                'value': 'false',
                'default_value': 'false',
            },
            {
                'key': 'PARALLEL_APPROVALS_ENABLED',
                'display_name': 'Enable Parallel Approvals',
                'description': 'Allow multiple approvers at same level to approve simultaneously',
                'category': 'workflow',
                'setting_type': 'boolean',
                'value': 'false',
                'default_value': 'false',
            },
            {
                'key': 'APPROVAL_SLA_HOURS',
                'display_name': 'Approval SLA (Hours)',
                'description': 'Target turnaround time for approval actions',
                'category': 'workflow',
                'setting_type': 'integer',
                'value': '48',
                'default_value': '48',
            },
            {
                'key': 'PAYMENT_SLA_HOURS',
                'display_name': 'Payment SLA (Hours)',
                'description': 'Target turnaround time for payment execution after approval',
                'category': 'workflow',
                'setting_type': 'integer',
                'value': '24',
                'default_value': '24',
            },
            {
                'key': 'END_TO_END_SLA_DAYS',
                'display_name': 'End-to-End SLA (Days)',
                'description': 'Total target time from requisition submission to payment',
                'category': 'workflow',
                'setting_type': 'integer',
                'value': '5',
                'default_value': '5',
            },
            {
                'key': 'OVERDUE_THRESHOLD_HOURS',
                'display_name': 'Overdue Threshold (Hours)',
                'description': 'Mark requisition as overdue after N hours without action',
                'category': 'workflow',
                'setting_type': 'integer',
                'value': '72',
                'default_value': '72',
            },
            {
                'key': 'CRITICAL_OVERDUE_HOURS',
                'display_name': 'Critical Overdue Threshold (Hours)',
                'description': 'Flag as critical/urgent when overdue exceeds this threshold',
                'category': 'workflow',
                'setting_type': 'integer',
                'value': '120',
                'default_value': '120',
            },
            {
                'key': 'SEND_OVERDUE_ALERTS',
                'display_name': 'Send Overdue Alerts',
                'description': 'Send email alerts when requisitions become overdue',
                'category': 'workflow',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'OVERDUE_ALERT_RECIPIENTS',
                'display_name': 'Overdue Alert Recipients',
                'description': 'Additional recipients for overdue alerts (comma-separated emails)',
                'category': 'workflow',
                'setting_type': 'string',
                'value': 'admin@company.local',
                'default_value': 'admin@company.local',
            },
            {
                'key': 'TRACK_WORKFLOW_METRICS',
                'display_name': 'Track Workflow Metrics',
                'description': 'Enable tracking of TAT, SLA compliance, and bottleneck analysis',
                'category': 'workflow',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'AUTO_APPROVE_BELOW_THRESHOLD',
                'display_name': 'Auto-Approve Below Threshold',
                'description': 'Automatically approve requisitions below minimum amount (risky)',
                'category': 'workflow',
                'setting_type': 'boolean',
                'value': 'false',
                'default_value': 'false',
            },
            {
                'key': 'DELEGATE_APPROVALS_ENABLED',
                'display_name': 'Enable Approval Delegation',
                'description': 'Allow approvers to delegate their authority to others',
                'category': 'workflow',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            
            # ORGANIZATION SETTINGS
            {
                'key': 'ALLOW_USER_SELF_REGISTRATION',
                'display_name': 'Allow User Self-Registration',
                'description': 'Enable users to register accounts themselves (requires admin approval)',
                'category': 'organization',
                'setting_type': 'boolean',
                'value': 'false',
                'default_value': 'false',
            },
            {
                'key': 'REQUIRE_EMAIL_VERIFICATION',
                'display_name': 'Require Email Verification',
                'description': 'Users must verify email before accessing the system',
                'category': 'organization',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'DEFAULT_USER_ROLE',
                'display_name': 'Default User Role',
                'description': 'Default role assigned to new users',
                'category': 'organization',
                'setting_type': 'string',
                'value': 'requester',
                'default_value': 'requester',
            },
            {
                'key': 'MULTI_DEPARTMENT_ACCESS',
                'display_name': 'Allow Multi-Department Access',
                'description': 'Allow users to belong to multiple departments',
                'category': 'organization',
                'setting_type': 'boolean',
                'value': 'false',
                'default_value': 'false',
            },
            {
                'key': 'ENFORCE_DEPARTMENT_HIERARCHY',
                'display_name': 'Enforce Department Hierarchy',
                'description': 'Restrict access based on department reporting structure',
                'category': 'organization',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'MAX_USERS_PER_DEPARTMENT',
                'display_name': 'Max Users Per Department',
                'description': 'Maximum number of users allowed per department (0 for unlimited)',
                'category': 'organization',
                'setting_type': 'integer',
                'value': '0',
                'default_value': '0',
            },
            {
                'key': 'ROLE_CHANGE_REQUIRES_APPROVAL',
                'display_name': 'Role Change Requires Approval',
                'description': 'Role changes must be approved by admin/superuser',
                'category': 'organization',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'AUTO_DEACTIVATE_INACTIVE_DAYS',
                'display_name': 'Auto-Deactivate After Inactivity (Days)',
                'description': 'Automatically deactivate users after N days of inactivity (0 to disable)',
                'category': 'organization',
                'setting_type': 'integer',
                'value': '90',
                'default_value': '90',
            },
            {
                'key': 'ALLOWED_USER_ROLES',
                'display_name': 'Allowed User Roles',
                'description': 'Comma-separated list of roles that can be assigned',
                'category': 'organization',
                'setting_type': 'string',
                'value': 'requester,department_head,group_finance_manager,cfo,ceo,treasury,fp&a,admin',
                'default_value': 'requester,department_head,group_finance_manager,cfo,ceo,treasury,fp&a,admin',
            },
            {
                'key': 'DEPARTMENT_CREATION_RESTRICTED',
                'display_name': 'Restrict Department Creation',
                'description': 'Only admins can create new departments',
                'category': 'organization',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'USER_PROFILE_FIELDS_REQUIRED',
                'display_name': 'Required User Profile Fields',
                'description': 'Comma-separated fields required in user profile (e.g., phone,employee_id)',
                'category': 'organization',
                'setting_type': 'string',
                'value': 'email,first_name,last_name,department',
                'default_value': 'email,first_name,last_name,department',
            },
            {
                'key': 'ENABLE_USER_DELEGATION',
                'display_name': 'Enable User Delegation',
                'description': 'Allow users to delegate their tasks when on leave',
                'category': 'organization',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'TRACK_USER_LOGIN_HISTORY',
                'display_name': 'Track User Login History',
                'description': 'Maintain log of user login times and IP addresses',
                'category': 'organization',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
            {
                'key': 'CONCURRENT_SESSIONS_ALLOWED',
                'display_name': 'Concurrent Sessions Per User',
                'description': 'Number of concurrent logins allowed (0 for unlimited)',
                'category': 'organization',
                'setting_type': 'integer',
                'value': '1',
                'default_value': '1',
            },
            {
                'key': 'DISPLAY_USER_HIERARCHY',
                'display_name': 'Display User Hierarchy',
                'description': 'Show organizational chart/hierarchy in user interface',
                'category': 'organization',
                'setting_type': 'boolean',
                'value': 'true',
                'default_value': 'true',
            },
        ]
        
        created_count = 0
        updated_count = 0
        
        for setting_data in settings:
            setting, created = SystemSetting.objects.update_or_create(
                key=setting_data['key'],
                defaults=setting_data
            )
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'✓ Created: {setting.display_name}'))
            else:
                updated_count += 1
                self.stdout.write(f'  Updated: {setting.display_name}')
        
        self.stdout.write(self.style.SUCCESS(f'\n✓ Seeded {created_count} new settings, updated {updated_count} existing'))
        
        # Summary by category
        category_counts = {}
        for setting in SystemSetting.objects.filter(is_active=True):
            category_counts[setting.category] = category_counts.get(setting.category, 0) + 1
        
        self.stdout.write('\nSettings by category:')
        for category, count in sorted(category_counts.items()):
            self.stdout.write(f'  {category.title()}: {count}')
