# Generated by Django 5.2.7 on 2025-10-18 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalthreshold',
            options={'ordering': ['priority', 'min_amount'], 'verbose_name': 'Approval Threshold', 'verbose_name_plural': 'Approval Thresholds'},
        ),
        migrations.RemoveField(
            model_name='approvalthreshold',
            name='description',
        ),
        migrations.AddField(
            model_name='approvalthreshold',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='approvalthreshold',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='approvalthreshold',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Tier name, e.g. Tier 1, Tier 2', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvalthreshold',
            name='origin_type',
            field=models.CharField(choices=[('BRANCH', 'Branch'), ('HQ', 'HQ'), ('FIELD', 'Field'), ('ANY', 'Any')], default='ANY', max_length=16),
        ),
        migrations.AddField(
            model_name='approvalthreshold',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Lower = higher priority when multiple thresholds overlap.'),
        ),
        migrations.AddField(
            model_name='approvalthreshold',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='approvalthreshold',
            name='allow_urgent_fasttrack',
            field=models.BooleanField(default=False, help_text='If True, urgent requisitions may skip intermediate levels where allowed.'),
        ),
        migrations.AlterField(
            model_name='approvalthreshold',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=999999999, max_digits=14),
        ),
        migrations.AlterField(
            model_name='approvalthreshold',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='approvalthreshold',
            name='requires_cfo',
            field=models.BooleanField(default=False, help_text='True if CFO approval is mandatory (usually Tier 4).'),
        ),
        migrations.AlterField(
            model_name='approvalthreshold',
            name='roles_sequence',
            field=models.JSONField(help_text="Ordered list of roles, e.g. ['Branch Manager','Treasury']"),
        ),
        migrations.AddIndex(
            model_name='approvalthreshold',
            index=models.Index(fields=['origin_type', 'min_amount', 'max_amount'], name='workflow_ap_origin__0604eb_idx'),
        ),
    ]
